global:
  resolve_timeout: 5m

route:
  receiver: 'feishu-webhook'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m

receivers:
  - name: 'feishu-webhook'
    webhook_configs:
      - url: 'http://alertmanager-lark-adapter:8060/alert'
        send_resolved: true
