groups:
  - name: docker_alerts
    rules:
      - alert: ContainerDown
        expr: docker_container_status_pid == 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: "{{$labels.container_name}}: Container is down"
          description: "{{$labels.container_name}}: Container on host {{$labels.engine_host}} has stopped."

      - alert: ContainerRestartTooManyTimes
        expr: increase(docker_container_status_restart_count[1m]) > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{$labels.container_name}}: Container restart too many times"
          description: "{{$labels.container_name}}: Container {{$labels.container_name}} restart too many times, now reach {{$value}}"

      - alert: ContainerMemoryUsageTooHigh
        expr: docker_container_mem_usage_percent > 75
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{$labels.container_name}}: Container memory usage too high"
          description: "{{$labels.container_name}}: Container memory usage exceeds 75%. (current usage: {{$value}})"

      - alert: ContainerCPUUsageTooHigh
        expr: docker_container_cpu_usage_percent > 200
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{$labels.container_name}}: Container CPU usage too high"
          description: "{{$labels.container_name}}: Container CPU usage high (current usage: {{$value}})"