global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting settings
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Location of alerting rules
rule_files:
  - '/etc/prometheus/alert_rules.yml'

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: docker-status
    scrape_interval: 3s
    metrics_path: /metrics
    static_configs:
      - targets:
          - telegraf:9273
